### ISSUE TITLE
Theme files.

### ISSUE THREAD

**Issue by rediffusion** [obrejla/vscode-netbeans-light-theme#13]
Good evening! 🎈 ☀️

Why in this place did I see **2 files**?
> C:\Users\MyPC\.vscode\extensions\obrejla.netbeans-light-theme-2.0.2\themes\

NetBeansLight.json
NetBeansLight.tmTheme

I find that this file works very well:

> NetBeansLight.json

 _the questions is why there's this file:

> NetBeansLight.tmTheme 

...with regards❗

**Comment by obrejla** [comment]
Hi, as far as I remember (it's 3 years already), there was only support for `.tmTheme` theme file. But then VSC introduced support also for `.json` based themes. And imho that json format was more flexible. So `.tmTheme` is here just for historic reasons. Most likely not needed anymore.
