### ISSUE TITLE
Bold function names

### ISSUE THREAD

**Issue by amariq** [obrejla/vscode-netbeans-light-theme#2]
See the title :P

AFAIR, function names are always marked bold in NetBeans (as well as explicit plain objects, actually).

Nice and very similar theme anyway, thanks!

**Comment by obrejla** [comment]
Hi! Thanks ;) 

Yep I know, the problem in VS Code is that there is no semantic coloring (afaik), so you can either have "all function names" bold (including declarations and usages) or nothing. I tried that "bold" style, but it did not look good so I decided not to use it :)

**Comment by amariq** [comment]
Hmm... Yeah, but I'd rather have all function names and plain objects bold. Yes, it's different from NetBeans style a bit, but lesser than without using bold at all and also it would add some more readability :)

UPD. Oh, and one more thing! What about those ones at the picture? :P
![default](https://user-images.githubusercontent.com/13599452/27165767-a464416c-51af-11e7-8b70-af70e5e1f254.PNG)

**Comment by obrejla** [comment]
As I wrote, I tried that bold functions etc, but it dramatically decreased readability. At least for me...it's much readable to have it plain.

Sorry, not sure what you think by that img, can you explain it better? Thanks! :-)

**Comment by amariq** [comment]
Ok then, it's up to you =)
But maybe you could make separate version with bold names... :3

And the image: this is so-called "Indent Guides" (see "**editor.renderIndentGuides**" option) from NetBeans, pretty useful as to me. But in Code they are just plain white... like the editor background color :P

**Comment by obrejla** [comment]
I'll look at that bold functions again, we will see.

Yep I thought that, I do not use it, so it was not clear to me ;)

Thanks!

**Comment by obrejla** [comment]
You can use this to have a gray indent guides in VS Code, just put it in your settings. Not sure whether it is possible to provide such setting through extension.

```
    "editor.renderIndentGuides": true,
    "workbench.colorCustomizations": {
        "editorIndentGuide.background": "#D3D3D3"
    },
```

**Comment by obrejla** [comment]
I also updated a theme a bit (v1.1.1) so function declaration should be bold. At least some of them ;)

**Comment by obrejla** [comment]
And of course, don't hesitate to "star" the extension :-D Well, it's up to you of course ;-))) Thanks!

**Comment by amariq** [comment]
> You can use this to have a gray indent guides in VS Code, just put it in your 

> settings.

Wow, didn't know this is possible. But I think such solution overrides theme settings, right? Isn't it possible to set guide lines color through theme settings?

**Comment by obrejla** [comment]
Unfortunately, I don't see the place where to put it in :/ It's more likely about "editor" styling, not "code" styling...not sure whether it is even possible to put it to the extension.

I'll put it there when I find the right place, but until that happen...use user setting :)

**Comment by amariq** [comment]
Hmm... But other themes do set their own guide lines color, strange (at least builtin ones) :O

**Comment by obrejla** [comment]
Hmhm, I'll need to look at it.

**Comment by obrejla** [comment]
I'll fill separate issue for that - #4
