### ISSUE TITLE
Support for Typescript files as well

### ISSUE THREAD

**Issue by developxible** [obrejla/vscode-netbeans-light-theme#3]
Typescript files are not rendered like the Javascript ones. Is there a way to have .ts files supported and, at least, they share the same highlighting with .js files?

Thanks.

**Comment by obrejla** [comment]
Hi,
once I'll have a time, I'll look at it :-)
Thanks!

**Comment by obrejla** [comment]
Fixed in master #842e733f and v1.1.0.

**Comment by obrejla** [comment]
And of course, don't hesitate to "star" the extension :-D Well, it's up to you of course ;-))) Thanks!
