### ISSUE TITLE
Some styling differences

### ISSUE THREAD

**Issue by amariq** [obrejla/vscode-netbeans-light-theme#5]
Is it possible to achive this styling?
![default](https://user-images.githubusercontent.com/13599452/27228999-4bdce020-52c3-11e7-93d3-e745a3ed387c.PNG)

Currently it styled as this:
![2](https://user-images.githubusercontent.com/13599452/27229015-5f9d3038-52c3-11e7-9f2c-929e6534e238.PNG)

Thanks! :3

**Comment by obrejla** [comment]
Will evaluate later, do not have any time left right now :)

**Comment by obrejla** [comment]
Hmhm, I don't see the way how to do that to not break some other property coloring...there seems to be no difference scopes :/ Sry.

**Comment by amariq** [comment]
Even with updated theming API? Sad :-(

P.S. Is it scopes? I think NetBeans simply marks all primitive properties with green color, and objects are bold...

**Comment by obrejla** [comment]
I meant the "scopes" in VS Code, the scope for for `bar` and `baz` in this `foo.bar.baz = 1` seems to be in fact the same as for `foo.bar.baz = {}`.

NetBeans uses 2 types of colorings...common Lexer based and semantic based on AST. I think that the "object" coloring is that semantic one.

**Comment by amariq** [comment]
Okay, I see, thanks :)

**Comment by obrejla** [comment]
You are welcome!
